version: '3'

services:
  xentral:
    image:  lobaro/xentral-docker:latest
    ports:
      - "8881:80"
    restart: always
    volumes:
#      - xentral:/var/www/html
      - ./web:/var/www/html/www/web
volumes:
  xentral:
